// Generated by SwiftTZGenerator. Do not edit.

import Foundation

/// Time zone identifiers from IANA Time Zone Database
public enum TimeZoneIdentifier: String, CaseIterable, Hashable {
    /// The source type of the timezone
    public enum Source: String {
        /// From zonenow.tab - currently active timezones
        case now
        /// From zone1970.tab - historical timezones since 1970
        case zone1970
    }
    
        /// Historical timezone from zone1970.tab
    case americaArgentinaRioGallegos = "America/Argentina/Rio_Gallegos"
            /// Historical timezone from zone1970.tab
    case asiaNicosia = "Asia/Nicosia"
            /// Historical timezone from zone1970.tab
    case europeVolgograd = "Europe/Volgograd"
            /// Historical timezone from zone1970.tab
    case asiaMagadan = "Asia/Magadan"
            /// Historical timezone from zone1970.tab
    case americaNorthDakotaCenter = "America/North_Dakota/Center"
            /// Current timezone from zonenow.tab
    case africaAbidjan = "Africa/Abidjan"
            /// Current timezone from zonenow.tab
    case asiaBeirut = "Asia/Beirut"
            /// Current timezone from zonenow.tab
    case asiaJayapura = "Asia/Jayapura"
            /// Historical timezone from zone1970.tab
    case americaDetroit = "America/Detroit"
            /// Historical timezone from zone1970.tab
    case americaIndianaVincennes = "America/Indiana/Vincennes"
            /// Current timezone from zonenow.tab
    case asiaKabul = "Asia/Kabul"
            /// Historical timezone from zone1970.tab
    case antarcticaVostok = "Antarctica/Vostok"
            /// Historical timezone from zone1970.tab
    case americaFortaleza = "America/Fortaleza"
            /// Current timezone from zonenow.tab
    case pacificHonolulu = "Pacific/Honolulu"
            /// Historical timezone from zone1970.tab
    case asiaOmsk = "Asia/Omsk"
            /// Historical timezone from zone1970.tab
    case americaKentuckyMonticello = "America/Kentucky/Monticello"
            /// Current timezone from zonenow.tab
    case asiaBangkok = "Asia/Bangkok"
            /// Historical timezone from zone1970.tab
    case americaInuvik = "America/Inuvik"
            /// Historical timezone from zone1970.tab
    case americaArgentinaCatamarca = "America/Argentina/Catamarca"
            /// Historical timezone from zone1970.tab
    case americaBahiaBanderas = "America/Bahia_Banderas"
            /// Historical timezone from zone1970.tab
    case americaRankinInlet = "America/Rankin_Inlet"
            /// Historical timezone from zone1970.tab
    case americaIqaluit = "America/Iqaluit"
            /// Historical timezone from zone1970.tab
    case asiaHebron = "Asia/Hebron"
            /// Historical timezone from zone1970.tab
    case americaToronto = "America/Toronto"
            /// Historical timezone from zone1970.tab
    case asiaUlaanbaatar = "Asia/Ulaanbaatar"
            /// Historical timezone from zone1970.tab
    case americaFortNelson = "America/Fort_Nelson"
            /// Current timezone from zonenow.tab
    case americaLima = "America/Lima"
            /// Current timezone from zonenow.tab
    case pacificGuam = "Pacific/Guam"
            /// Historical timezone from zone1970.tab
    case europeSaratov = "Europe/Saratov"
            /// Historical timezone from zone1970.tab
    case pacificKanton = "Pacific/Kanton"
            /// Current timezone from zonenow.tab
    case asiaJakarta = "Asia/Jakarta"
            /// Current timezone from zonenow.tab
    case pacificBougainville = "Pacific/Bougainville"
            /// Historical timezone from zone1970.tab
    case atlanticCanary = "Atlantic/Canary"
            /// Historical timezone from zone1970.tab
    case asiaPontianak = "Asia/Pontianak"
            /// Historical timezone from zone1970.tab
    case africaCeuta = "Africa/Ceuta"
            /// Current timezone from zonenow.tab
    case asiaSingapore = "Asia/Singapore"
            /// Historical timezone from zone1970.tab
    case americaNorthDakotaBeulah = "America/North_Dakota/Beulah"
            /// Historical timezone from zone1970.tab
    case americaMetlakatla = "America/Metlakatla"
            /// Current timezone from zonenow.tab
    case asiaGaza = "Asia/Gaza"
            /// Current timezone from zonenow.tab
    case asiaHongKong = "Asia/Hong_Kong"
            /// Historical timezone from zone1970.tab
    case americaGuayaquil = "America/Guayaquil"
            /// Current timezone from zonenow.tab
    case americaHavana = "America/Havana"
            /// Historical timezone from zone1970.tab
    case asiaYekaterinburg = "Asia/Yekaterinburg"
            /// Historical timezone from zone1970.tab
    case asiaYakutsk = "Asia/Yakutsk"
            /// Historical timezone from zone1970.tab
    case americaSantarem = "America/Santarem"
            /// Current timezone from zonenow.tab
    case pacificEaster = "Pacific/Easter"
            /// Historical timezone from zone1970.tab
    case americaPuntaArenas = "America/Punta_Arenas"
            /// Historical timezone from zone1970.tab
    case americaArgentinaSanLuis = "America/Argentina/San_Luis"
            /// Historical timezone from zone1970.tab
    case americaIndianaVevay = "America/Indiana/Vevay"
            /// Historical timezone from zone1970.tab
    case americaJuneau = "America/Juneau"
            /// Historical timezone from zone1970.tab
    case americaCambridgeBay = "America/Cambridge_Bay"
            /// Historical timezone from zone1970.tab
    case americaDawson = "America/Dawson"
            /// Historical timezone from zone1970.tab
    case americaArgentinaUshuaia = "America/Argentina/Ushuaia"
            /// Current timezone from zonenow.tab
    case americaStJohns = "America/St_Johns"
            /// Current timezone from zonenow.tab
    case europeParis = "Europe/Paris"
            /// Historical timezone from zone1970.tab
    case americaWhitehorse = "America/Whitehorse"
            /// Historical timezone from zone1970.tab
    case pacificTarawa = "Pacific/Tarawa"
            /// Historical timezone from zone1970.tab
    case asiaNovosibirsk = "Asia/Novosibirsk"
            /// Current timezone from zonenow.tab
    case americaNewYork = "America/New_York"
            /// Current timezone from zonenow.tab
    case asiaDhaka = "Asia/Dhaka"
            /// Current timezone from zonenow.tab
    case europeIstanbul = "Europe/Istanbul"
            /// Historical timezone from zone1970.tab
    case americaTijuana = "America/Tijuana"
            /// Historical timezone from zone1970.tab
    case americaArgentinaJujuy = "America/Argentina/Jujuy"
            /// Current timezone from zonenow.tab
    case europeLondon = "Europe/London"
            /// Current timezone from zonenow.tab
    case asiaChita = "Asia/Chita"
            /// Historical timezone from zone1970.tab
    case americaEdmonton = "America/Edmonton"
            /// Current timezone from zonenow.tab
    case antarcticaTroll = "Antarctica/Troll"
            /// Historical timezone from zone1970.tab
    case indianMaldives = "Indian/Maldives"
            /// Historical timezone from zone1970.tab
    case asiaKrasnoyarsk = "Asia/Krasnoyarsk"
            /// Current timezone from zonenow.tab
    case americaMexicoCity = "America/Mexico_City"
            /// Historical timezone from zone1970.tab
    case americaWinnipeg = "America/Winnipeg"
            /// Historical timezone from zone1970.tab
    case asiaAlmaty = "Asia/Almaty"
            /// Current timezone from zonenow.tab
    case asiaKathmandu = "Asia/Kathmandu"
            /// Current timezone from zonenow.tab
    case pacificAuckland = "Pacific/Auckland"
            /// Current timezone from zonenow.tab
    case asiaMakassar = "Asia/Makassar"
            /// Historical timezone from zone1970.tab
    case pacificKwajalein = "Pacific/Kwajalein"
            /// Historical timezone from zone1970.tab
    case americaIndianaMarengo = "America/Indiana/Marengo"
            /// Current timezone from zonenow.tab
    case pacificChatham = "Pacific/Chatham"
            /// Historical timezone from zone1970.tab
    case americaYakutat = "America/Yakutat"
            /// Current timezone from zonenow.tab
    case americaDenver = "America/Denver"
            /// Current timezone from zonenow.tab
    case asiaManila = "Asia/Manila"
            /// Current timezone from zonenow.tab
    case asiaTokyo = "Asia/Tokyo"
            /// Historical timezone from zone1970.tab
    case asiaSamarkand = "Asia/Samarkand"
            /// Historical timezone from zone1970.tab
    case americaMatamoros = "America/Matamoros"
            /// Current timezone from zonenow.tab
    case asiaKarachi = "Asia/Karachi"
            /// Current timezone from zonenow.tab
    case europeChisinau = "Europe/Chisinau"
            /// Historical timezone from zone1970.tab
    case asiaNovokuznetsk = "Asia/Novokuznetsk"
            /// Historical timezone from zone1970.tab
    case australiaHobart = "Australia/Hobart"
            /// Current timezone from zonenow.tab
    case pacificTahiti = "Pacific/Tahiti"
            /// Historical timezone from zone1970.tab
    case americaBoise = "America/Boise"
            /// Historical timezone from zone1970.tab
    case pacificGuadalcanal = "Pacific/Guadalcanal"
            /// Historical timezone from zone1970.tab
    case americaHermosillo = "America/Hermosillo"
            /// Historical timezone from zone1970.tab
    case americaScoresbysund = "America/Scoresbysund"
            /// Current timezone from zonenow.tab
    case asiaColombo = "Asia/Colombo"
            /// Historical timezone from zone1970.tab
    case americaOjinaga = "America/Ojinaga"
            /// Historical timezone from zone1970.tab
    case australiaLindeman = "Australia/Lindeman"
            /// Historical timezone from zone1970.tab
    case antarcticaDavis = "Antarctica/Davis"
            /// Historical timezone from zone1970.tab
    case americaMaceio = "America/Maceio"
            /// Historical timezone from zone1970.tab
    case americaNorthDakotaNewSalem = "America/North_Dakota/New_Salem"
            /// Historical timezone from zone1970.tab
    case americaRioBranco = "America/Rio_Branco"
            /// Current timezone from zonenow.tab
    case americaSantoDomingo = "America/Santo_Domingo"
            /// Historical timezone from zone1970.tab
    case americaArgentinaLaRioja = "America/Argentina/La_Rioja"
            /// Historical timezone from zone1970.tab
    case americaMenominee = "America/Menominee"
            /// Current timezone from zonenow.tab
    case asiaKolkata = "Asia/Kolkata"
            /// Current timezone from zonenow.tab
    case australiaLordHowe = "Australia/Lord_Howe"
            /// Current timezone from zonenow.tab
    case americaNoronha = "America/Noronha"
            /// Historical timezone from zone1970.tab
    case americaArgentinaSalta = "America/Argentina/Salta"
            /// Historical timezone from zone1970.tab
    case antarcticaRothera = "Antarctica/Rothera"
            /// Current timezone from zonenow.tab
    case atlanticCapeVerde = "Atlantic/Cape_Verde"
            /// Historical timezone from zone1970.tab
    case americaResolute = "America/Resolute"
            /// Current timezone from zonenow.tab
    case australiaSydney = "Australia/Sydney"
            /// Current timezone from zonenow.tab
    case australiaAdelaide = "Australia/Adelaide"
            /// Historical timezone from zone1970.tab
    case antarcticaPalmer = "Antarctica/Palmer"
            /// Historical timezone from zone1970.tab
    case asiaUrumqi = "Asia/Urumqi"
            /// Historical timezone from zone1970.tab
    case europeSimferopol = "Europe/Simferopol"
            /// Current timezone from zonenow.tab
    case australiaEucla = "Australia/Eucla"
            /// Historical timezone from zone1970.tab
    case asiaQyzylorda = "Asia/Qyzylorda"
            /// Historical timezone from zone1970.tab
    case europeMadrid = "Europe/Madrid"
            /// Current timezone from zonenow.tab
    case asiaYangon = "Asia/Yangon"
            /// Historical timezone from zone1970.tab
    case americaRegina = "America/Regina"
            /// Historical timezone from zone1970.tab
    case europeSamara = "Europe/Samara"
            /// Historical timezone from zone1970.tab
    case asiaBarnaul = "Asia/Barnaul"
            /// Historical timezone from zone1970.tab
    case americaGooseBay = "America/Goose_Bay"
            /// Historical timezone from zone1970.tab
    case americaCampoGrande = "America/Campo_Grande"
            /// Current timezone from zonenow.tab
    case pacificNiue = "Pacific/Niue"
            /// Historical timezone from zone1970.tab
    case americaCuiaba = "America/Cuiaba"
            /// Historical timezone from zone1970.tab
    case europeUlyanovsk = "Europe/Ulyanovsk"
            /// Historical timezone from zone1970.tab
    case asiaFamagusta = "Asia/Famagusta"
            /// Current timezone from zonenow.tab
    case asiaTashkent = "Asia/Tashkent"
            /// Historical timezone from zone1970.tab
    case americaManaus = "America/Manaus"
            /// Historical timezone from zone1970.tab
    case americaMazatlan = "America/Mazatlan"
            /// Historical timezone from zone1970.tab
    case americaDanmarkshavn = "America/Danmarkshavn"
            /// Current timezone from zonenow.tab
    case americaAdak = "America/Adak"
            /// Current timezone from zonenow.tab
    case europeLisbon = "Europe/Lisbon"
            /// Historical timezone from zone1970.tab
    case atlanticMadeira = "Atlantic/Madeira"
            /// Current timezone from zonenow.tab
    case australiaDarwin = "Australia/Darwin"
            /// Historical timezone from zone1970.tab
    case antarcticaMawson = "Antarctica/Mawson"
            /// Current timezone from zonenow.tab
    case americaJamaica = "America/Jamaica"
            /// Historical timezone from zone1970.tab
    case antarcticaCasey = "Antarctica/Casey"
            /// Historical timezone from zone1970.tab
    case americaSwiftCurrent = "America/Swift_Current"
            /// Historical timezone from zone1970.tab
    case asiaAnadyr = "Asia/Anadyr"
            /// Historical timezone from zone1970.tab
    case americaArgentinaCordoba = "America/Argentina/Cordoba"
            /// Historical timezone from zone1970.tab
    case asiaAqtobe = "Asia/Aqtobe"
            /// Historical timezone from zone1970.tab
    case asiaAqtau = "Asia/Aqtau"
            /// Current timezone from zonenow.tab
    case pacificPagoPago = "Pacific/Pago_Pago"
            /// Historical timezone from zone1970.tab
    case americaEirunepe = "America/Eirunepe"
            /// Current timezone from zonenow.tab
    case africaTripoli = "Africa/Tripoli"
            /// Current timezone from zonenow.tab
    case africaAlgiers = "Africa/Algiers"
            /// Current timezone from zonenow.tab
    case pacificPitcairn = "Pacific/Pitcairn"
            /// Historical timezone from zone1970.tab
    case asiaAtyrau = "Asia/Atyrau"
            /// Historical timezone from zone1970.tab
    case americaPanama = "America/Panama"
            /// Current timezone from zonenow.tab
    case americaPhoenix = "America/Phoenix"
            /// Historical timezone from zone1970.tab
    case americaBelem = "America/Belem"
            /// Historical timezone from zone1970.tab
    case americaBahia = "America/Bahia"
            /// Historical timezone from zone1970.tab
    case asiaTomsk = "Asia/Tomsk"
            /// Historical timezone from zone1970.tab
    case asiaUstnera = "Asia/Ust-Nera"
            /// Historical timezone from zone1970.tab
    case asiaSakhalin = "Asia/Sakhalin"
            /// Historical timezone from zone1970.tab
    case europeKyiv = "Europe/Kyiv"
            /// Historical timezone from zone1970.tab
    case asiaKhandyga = "Asia/Khandyga"
            /// Current timezone from zonenow.tab
    case africaCasablanca = "Africa/Casablanca"
            /// Historical timezone from zone1970.tab
    case asiaQostanay = "Asia/Qostanay"
            /// Historical timezone from zone1970.tab
    case asiaHovd = "Asia/Hovd"
            /// Historical timezone from zone1970.tab
    case europeKaliningrad = "Europe/Kaliningrad"
            /// Historical timezone from zone1970.tab
    case americaArgentinaSanJuan = "America/Argentina/San_Juan"
            /// Historical timezone from zone1970.tab
    case asiaSrednekolymsk = "Asia/Srednekolymsk"
            /// Current timezone from zonenow.tab
    case asiaTehran = "Asia/Tehran"
            /// Historical timezone from zone1970.tab
    case europeZurich = "Europe/Zurich"
            /// Historical timezone from zone1970.tab
    case americaCancun = "America/Cancun"
            /// Current timezone from zonenow.tab
    case australiaPerth = "Australia/Perth"
            /// Current timezone from zonenow.tab
    case africaMaputo = "Africa/Maputo"
            /// Historical timezone from zone1970.tab
    case europeKirov = "Europe/Kirov"
            /// Historical timezone from zone1970.tab
    case americaMoncton = "America/Moncton"
            /// Historical timezone from zone1970.tab
    case americaVancouver = "America/Vancouver"
            /// Current timezone from zonenow.tab
    case pacificGalapagos = "Pacific/Galapagos"
            /// Historical timezone from zone1970.tab
    case antarcticaMacquarie = "Antarctica/Macquarie"
            /// Historical timezone from zone1970.tab
    case americaNome = "America/Nome"
            /// Current timezone from zonenow.tab
    case americaMiquelon = "America/Miquelon"
            /// Historical timezone from zone1970.tab
    case pacificPortMoresby = "Pacific/Port_Moresby"
            /// Historical timezone from zone1970.tab
    case americaDawsonCreek = "America/Dawson_Creek"
            /// Current timezone from zonenow.tab
    case americaCaracas = "America/Caracas"
            /// Historical timezone from zone1970.tab
    case americaKentuckyLouisville = "America/Kentucky/Louisville"
            /// Current timezone from zonenow.tab
    case pacificGambier = "Pacific/Gambier"
            /// Current timezone from zonenow.tab
    case americaSaoPaulo = "America/Sao_Paulo"
            /// Current timezone from zonenow.tab
    case asiaShanghai = "Asia/Shanghai"
            /// Historical timezone from zone1970.tab
    case americaBoaVista = "America/Boa_Vista"
            /// Historical timezone from zone1970.tab
    case americaChihuahua = "America/Chihuahua"
            /// Current timezone from zonenow.tab
    case americaHalifax = "America/Halifax"
            /// Historical timezone from zone1970.tab
    case americaIndianaKnox = "America/Indiana/Knox"
            /// Current timezone from zonenow.tab
    case pacificMarquesas = "Pacific/Marquesas"
            /// Current timezone from zonenow.tab
    case europeDublin = "Europe/Dublin"
            /// Current timezone from zonenow.tab
    case asiaKamchatka = "Asia/Kamchatka"
            /// Historical timezone from zone1970.tab
    case australiaBrokenHill = "Australia/Broken_Hill"
            /// Historical timezone from zone1970.tab
    case americaAraguaina = "America/Araguaina"
            /// Current timezone from zonenow.tab
    case europeMoscow = "Europe/Moscow"
            /// Historical timezone from zone1970.tab
    case asiaRiyadh = "Asia/Riyadh"
            /// Historical timezone from zone1970.tab
    case americaIndianaPetersburg = "America/Indiana/Petersburg"
            /// Historical timezone from zone1970.tab
    case americaArgentinaMendoza = "America/Argentina/Mendoza"
            /// Current timezone from zonenow.tab
    case americaAnchorage = "America/Anchorage"
            /// Historical timezone from zone1970.tab
    case europeAstrakhan = "Europe/Astrakhan"
            /// Historical timezone from zone1970.tab
    case americaIndianaTellCity = "America/Indiana/Tell_City"
            /// Historical timezone from zone1970.tab
    case americaPortoVelho = "America/Porto_Velho"
            /// Current timezone from zonenow.tab
    case americaChicago = "America/Chicago"
            /// Historical timezone from zone1970.tab
    case americaThule = "America/Thule"
            /// Current timezone from zonenow.tab
    case asiaDubai = "Asia/Dubai"
            /// Current timezone from zonenow.tab
    case americaNuuk = "America/Nuuk"
            /// Historical timezone from zone1970.tab
    case asiaIrkutsk = "Asia/Irkutsk"
            /// Current timezone from zonenow.tab
    case australiaBrisbane = "Australia/Brisbane"
            /// Historical timezone from zone1970.tab
    case americaArgentinaBuenosAires = "America/Argentina/Buenos_Aires"
            /// Current timezone from zonenow.tab
    case africaNairobi = "Africa/Nairobi"
            /// Current timezone from zonenow.tab
    case africaJohannesburg = "Africa/Johannesburg"
            /// Current timezone from zonenow.tab
    case pacificTongatapu = "Pacific/Tongatapu"
            /// Historical timezone from zone1970.tab
    case americaIndianaWinamac = "America/Indiana/Winamac"
            /// Historical timezone from zone1970.tab
    case americaArgentinaTucuman = "America/Argentina/Tucuman"
            /// Historical timezone from zone1970.tab
    case europeBerlin = "Europe/Berlin"
            /// Historical timezone from zone1970.tab
    case australiaMelbourne = "Australia/Melbourne"
            /// Current timezone from zonenow.tab
    case africaCairo = "Africa/Cairo"
            /// Historical timezone from zone1970.tab
    case americaIndianaIndianapolis = "America/Indiana/Indianapolis"
            /// Historical timezone from zone1970.tab
    case americaPuertoRico = "America/Puerto_Rico"
            /// Historical timezone from zone1970.tab
    case asiaHoChiMinh = "Asia/Ho_Chi_Minh"
            /// Historical timezone from zone1970.tab
    case pacificKosrae = "Pacific/Kosrae"
            /// Current timezone from zonenow.tab
    case americaSantiago = "America/Santiago"
            /// Current timezone from zonenow.tab
    case europeAthens = "Europe/Athens"
            /// Current timezone from zonenow.tab
    case asiaVladivostok = "Asia/Vladivostok"
            /// Current timezone from zonenow.tab
    case africaLagos = "Africa/Lagos"
            /// Historical timezone from zone1970.tab
    case americaRecife = "America/Recife"
            /// Current timezone from zonenow.tab
    case pacificNorfolk = "Pacific/Norfolk"
            /// Historical timezone from zone1970.tab
    case americaCiudadJuarez = "America/Ciudad_Juarez"
            /// Historical timezone from zone1970.tab
    case asiaKuching = "Asia/Kuching"
            /// Current timezone from zonenow.tab
    case atlanticAzores = "Atlantic/Azores"
            /// Current timezone from zonenow.tab
    case asiaSeoul = "Asia/Seoul"
            /// Current timezone from zonenow.tab
    case asiaJerusalem = "Asia/Jerusalem"
            /// Current timezone from zonenow.tab
    case americaLosAngeles = "America/Los_Angeles"
            /// Historical timezone from zone1970.tab
    case americaGlaceBay = "America/Glace_Bay"
            /// Historical timezone from zone1970.tab
    case americaMerida = "America/Merida"
            /// Historical timezone from zone1970.tab
    case americaSitka = "America/Sitka"
            /// Historical timezone from zone1970.tab
    case americaMonterrey = "America/Monterrey"
            /// Historical timezone from zone1970.tab
    case asiaOral = "Asia/Oral"
            /// Current timezone from zonenow.tab
    case pacificKiritimati = "Pacific/Kiritimati"
    
    /// Returns whether this timezone is from zonenow.tab or zone1970.tab
    public var source: Source {
        switch self {
            case .americaArgentinaRioGallegos: return .zone1970
                case .asiaNicosia: return .zone1970
                case .europeVolgograd: return .zone1970
                case .asiaMagadan: return .zone1970
                case .americaNorthDakotaCenter: return .zone1970
                case .africaAbidjan: return .now
                case .asiaBeirut: return .now
                case .asiaJayapura: return .now
                case .americaDetroit: return .zone1970
                case .americaIndianaVincennes: return .zone1970
                case .asiaKabul: return .now
                case .antarcticaVostok: return .zone1970
                case .americaFortaleza: return .zone1970
                case .pacificHonolulu: return .now
                case .asiaOmsk: return .zone1970
                case .americaKentuckyMonticello: return .zone1970
                case .asiaBangkok: return .now
                case .americaInuvik: return .zone1970
                case .americaArgentinaCatamarca: return .zone1970
                case .americaBahiaBanderas: return .zone1970
                case .americaRankinInlet: return .zone1970
                case .americaIqaluit: return .zone1970
                case .asiaHebron: return .zone1970
                case .americaToronto: return .zone1970
                case .asiaUlaanbaatar: return .zone1970
                case .americaFortNelson: return .zone1970
                case .americaLima: return .now
                case .pacificGuam: return .now
                case .europeSaratov: return .zone1970
                case .pacificKanton: return .zone1970
                case .asiaJakarta: return .now
                case .pacificBougainville: return .now
                case .atlanticCanary: return .zone1970
                case .asiaPontianak: return .zone1970
                case .africaCeuta: return .zone1970
                case .asiaSingapore: return .now
                case .americaNorthDakotaBeulah: return .zone1970
                case .americaMetlakatla: return .zone1970
                case .asiaGaza: return .now
                case .asiaHongKong: return .now
                case .americaGuayaquil: return .zone1970
                case .americaHavana: return .now
                case .asiaYekaterinburg: return .zone1970
                case .asiaYakutsk: return .zone1970
                case .americaSantarem: return .zone1970
                case .pacificEaster: return .now
                case .americaPuntaArenas: return .zone1970
                case .americaArgentinaSanLuis: return .zone1970
                case .americaIndianaVevay: return .zone1970
                case .americaJuneau: return .zone1970
                case .americaCambridgeBay: return .zone1970
                case .americaDawson: return .zone1970
                case .americaArgentinaUshuaia: return .zone1970
                case .americaStJohns: return .now
                case .europeParis: return .now
                case .americaWhitehorse: return .zone1970
                case .pacificTarawa: return .zone1970
                case .asiaNovosibirsk: return .zone1970
                case .americaNewYork: return .now
                case .asiaDhaka: return .now
                case .europeIstanbul: return .now
                case .americaTijuana: return .zone1970
                case .americaArgentinaJujuy: return .zone1970
                case .europeLondon: return .now
                case .asiaChita: return .now
                case .americaEdmonton: return .zone1970
                case .antarcticaTroll: return .now
                case .indianMaldives: return .zone1970
                case .asiaKrasnoyarsk: return .zone1970
                case .americaMexicoCity: return .now
                case .americaWinnipeg: return .zone1970
                case .asiaAlmaty: return .zone1970
                case .asiaKathmandu: return .now
                case .pacificAuckland: return .now
                case .asiaMakassar: return .now
                case .pacificKwajalein: return .zone1970
                case .americaIndianaMarengo: return .zone1970
                case .pacificChatham: return .now
                case .americaYakutat: return .zone1970
                case .americaDenver: return .now
                case .asiaManila: return .now
                case .asiaTokyo: return .now
                case .asiaSamarkand: return .zone1970
                case .americaMatamoros: return .zone1970
                case .asiaKarachi: return .now
                case .europeChisinau: return .now
                case .asiaNovokuznetsk: return .zone1970
                case .australiaHobart: return .zone1970
                case .pacificTahiti: return .now
                case .americaBoise: return .zone1970
                case .pacificGuadalcanal: return .zone1970
                case .americaHermosillo: return .zone1970
                case .americaScoresbysund: return .zone1970
                case .asiaColombo: return .now
                case .americaOjinaga: return .zone1970
                case .australiaLindeman: return .zone1970
                case .antarcticaDavis: return .zone1970
                case .americaMaceio: return .zone1970
                case .americaNorthDakotaNewSalem: return .zone1970
                case .americaRioBranco: return .zone1970
                case .americaSantoDomingo: return .now
                case .americaArgentinaLaRioja: return .zone1970
                case .americaMenominee: return .zone1970
                case .asiaKolkata: return .now
                case .australiaLordHowe: return .now
                case .americaNoronha: return .now
                case .americaArgentinaSalta: return .zone1970
                case .antarcticaRothera: return .zone1970
                case .atlanticCapeVerde: return .now
                case .americaResolute: return .zone1970
                case .australiaSydney: return .now
                case .australiaAdelaide: return .now
                case .antarcticaPalmer: return .zone1970
                case .asiaUrumqi: return .zone1970
                case .europeSimferopol: return .zone1970
                case .australiaEucla: return .now
                case .asiaQyzylorda: return .zone1970
                case .europeMadrid: return .zone1970
                case .asiaYangon: return .now
                case .americaRegina: return .zone1970
                case .europeSamara: return .zone1970
                case .asiaBarnaul: return .zone1970
                case .americaGooseBay: return .zone1970
                case .americaCampoGrande: return .zone1970
                case .pacificNiue: return .now
                case .americaCuiaba: return .zone1970
                case .europeUlyanovsk: return .zone1970
                case .asiaFamagusta: return .zone1970
                case .asiaTashkent: return .now
                case .americaManaus: return .zone1970
                case .americaMazatlan: return .zone1970
                case .americaDanmarkshavn: return .zone1970
                case .americaAdak: return .now
                case .europeLisbon: return .now
                case .atlanticMadeira: return .zone1970
                case .australiaDarwin: return .now
                case .antarcticaMawson: return .zone1970
                case .americaJamaica: return .now
                case .antarcticaCasey: return .zone1970
                case .americaSwiftCurrent: return .zone1970
                case .asiaAnadyr: return .zone1970
                case .americaArgentinaCordoba: return .zone1970
                case .asiaAqtobe: return .zone1970
                case .asiaAqtau: return .zone1970
                case .pacificPagoPago: return .now
                case .americaEirunepe: return .zone1970
                case .africaTripoli: return .now
                case .africaAlgiers: return .now
                case .pacificPitcairn: return .now
                case .asiaAtyrau: return .zone1970
                case .americaPanama: return .zone1970
                case .americaPhoenix: return .now
                case .americaBelem: return .zone1970
                case .americaBahia: return .zone1970
                case .asiaTomsk: return .zone1970
                case .asiaUstnera: return .zone1970
                case .asiaSakhalin: return .zone1970
                case .europeKyiv: return .zone1970
                case .asiaKhandyga: return .zone1970
                case .africaCasablanca: return .now
                case .asiaQostanay: return .zone1970
                case .asiaHovd: return .zone1970
                case .europeKaliningrad: return .zone1970
                case .americaArgentinaSanJuan: return .zone1970
                case .asiaSrednekolymsk: return .zone1970
                case .asiaTehran: return .now
                case .europeZurich: return .zone1970
                case .americaCancun: return .zone1970
                case .australiaPerth: return .now
                case .africaMaputo: return .now
                case .europeKirov: return .zone1970
                case .americaMoncton: return .zone1970
                case .americaVancouver: return .zone1970
                case .pacificGalapagos: return .now
                case .antarcticaMacquarie: return .zone1970
                case .americaNome: return .zone1970
                case .americaMiquelon: return .now
                case .pacificPortMoresby: return .zone1970
                case .americaDawsonCreek: return .zone1970
                case .americaCaracas: return .now
                case .americaKentuckyLouisville: return .zone1970
                case .pacificGambier: return .now
                case .americaSaoPaulo: return .now
                case .asiaShanghai: return .now
                case .americaBoaVista: return .zone1970
                case .americaChihuahua: return .zone1970
                case .americaHalifax: return .now
                case .americaIndianaKnox: return .zone1970
                case .pacificMarquesas: return .now
                case .europeDublin: return .now
                case .asiaKamchatka: return .now
                case .australiaBrokenHill: return .zone1970
                case .americaAraguaina: return .zone1970
                case .europeMoscow: return .now
                case .asiaRiyadh: return .zone1970
                case .americaIndianaPetersburg: return .zone1970
                case .americaArgentinaMendoza: return .zone1970
                case .americaAnchorage: return .now
                case .europeAstrakhan: return .zone1970
                case .americaIndianaTellCity: return .zone1970
                case .americaPortoVelho: return .zone1970
                case .americaChicago: return .now
                case .americaThule: return .zone1970
                case .asiaDubai: return .now
                case .americaNuuk: return .now
                case .asiaIrkutsk: return .zone1970
                case .australiaBrisbane: return .now
                case .americaArgentinaBuenosAires: return .zone1970
                case .africaNairobi: return .now
                case .africaJohannesburg: return .now
                case .pacificTongatapu: return .now
                case .americaIndianaWinamac: return .zone1970
                case .americaArgentinaTucuman: return .zone1970
                case .europeBerlin: return .zone1970
                case .australiaMelbourne: return .zone1970
                case .africaCairo: return .now
                case .americaIndianaIndianapolis: return .zone1970
                case .americaPuertoRico: return .zone1970
                case .asiaHoChiMinh: return .zone1970
                case .pacificKosrae: return .zone1970
                case .americaSantiago: return .now
                case .europeAthens: return .now
                case .asiaVladivostok: return .now
                case .africaLagos: return .now
                case .americaRecife: return .zone1970
                case .pacificNorfolk: return .now
                case .americaCiudadJuarez: return .zone1970
                case .asiaKuching: return .zone1970
                case .atlanticAzores: return .now
                case .asiaSeoul: return .now
                case .asiaJerusalem: return .now
                case .americaLosAngeles: return .now
                case .americaGlaceBay: return .zone1970
                case .americaMerida: return .zone1970
                case .americaSitka: return .zone1970
                case .americaMonterrey: return .zone1970
                case .asiaOral: return .zone1970
                case .pacificKiritimati: return .now
        }
    }
}